// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCBJtx51befCxChsGAfHHaYAOC11nKfeo',
    appId: '1:424970657652:web:2d141c104d62dc636bd621',
    messagingSenderId: '424970657652',
    projectId: 'barnashtawy-app',
    authDomain: 'barnashtawy-app.firebaseapp.com',
    storageBucket: 'barnashtawy-app.firebasestorage.app',
    measurementId: 'G-ZCRDCY8LLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC57rYug1Jf3zuwbieg6pb9OGN-hn3Bkv8',
    appId: '1:424970657652:android:7aa294873c2e3b3b6bd621',
    messagingSenderId: '424970657652',
    projectId: 'barnashtawy-app',
    storageBucket: 'barnashtawy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFtxXs4nIb0fGJoCVzMWAzRRIsfsWifwo',
    appId: '1:424970657652:ios:1300370e15ce51936bd621',
    messagingSenderId: '424970657652',
    projectId: 'barnashtawy-app',
    storageBucket: 'barnashtawy-app.firebasestorage.app',
    iosBundleId: 'com.example.barnashtApp',
  );
}
